name: pre-commit
on:
  pull_request:
  push:

jobs:
  pre-commit:
    name: pre-commit
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Set up Python 3.9.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.12
      - name: Setup
        run: pip install --requirement requirements.txt
      - name: pre-commit
        uses: pre-commit/action@v2.0.3
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
